name: legtransito
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  win32: ^5.5.4
  window_manager: ^0.4.2
  flutter_launcher_icons: ^0.14.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ltlogo.png

# Configuração para Flutter Launcher Icons
flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/images/ltlogo.png"
    icon_size: 48
